spring.application.name=Employee
# Configuration du serveur
server.port=8081

# Configuration de la base de donn�es MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/MembresDB?
spring.datasource.username=root
spring.datasource.password=

# Configuration Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
